header and hide fields
pa11y/pa11y-dashboard pull request #151
Opened 2016-10-17 11:24 UTC by lc512k

2016-10-19 01:14 UTC, rowanmanning commented
This looks great! I'll get it running locally ASAP and release a new version. Thanks for all the work :)

2016-10-20 13:20 UTC, rowanmanning requested changes

2016-10-20 13:20 UTC, rowanmanning commented on route/new.js
> +			hideElements: req.body.hide
Should this be `req.body['hide-elements']`?

2016-10-20 13:20 UTC, rowanmanning commented on view/new.html
> +				<input class="form-control" id="new-task-headers" type="text" name="headers" value="{{task.headers}}" placeholder='{headers: {"Cookie": "foo=bar"}}'/>
Should the placeholder here be just `{"Cookie": "foo=bar"}` rather than having the `headers` property in it?

2016-10-20 13:20 UTC, rowanmanning commented on view/task/edit.html
> +				<input class="form-control" id="new-task-headers" type="text" name="headers" value="{{task.headers}}" placeholder='{headers: {"Cookie": "foo=bar"}}'/>
Should the placeholder here be just `{"Cookie": "foo=bar"}` rather than having the `headers` property in it?

2016-10-25 07:00 UTC, lc512k commented
Thanks, @rowanmanning! Fixed.

2016-11-07 14:16 UTC, rowanmanning commented
I need to make a few changes to this and fix conflicts, so going to open a new PR with your work :)

2016-11-07 14:16 UTC, closed without merging