Improve installation instructions
pa11y/pa11y-dashboard pull request #278
Opened 2021-04-09 09:58 UTC by josebolos

* Clarify the requirements for running Pa11y Dashboard, and specifically the versions of MongoDB supported
* Split the installation process in sections so it's easy to follow
* Instead of trying to cover the MongoDB installation on the Readme, refer to the MongoDB docs, but still including a macOS example for easy reference
* Clarify the use of the config files and how they relate to the NODE_ENV variable
* Use a slightly less informal language in a few places

2021-04-09 10:27 UTC, sonniesedge commented on README.md
> +brew services start mongodb/brew/mongodb-community
This should be:
```
brew services start mongodb/brew/mongodb-community@3.4
```

2021-04-09 10:38 UTC, sonniesedge requested changes
Just need to specify the MongoDB version number when running the service and that's it.

2021-04-09 12:54 UTC, josebolos commented on README.md
> +brew services start mongodb/brew/mongodb-community
Good idea, done in `6bd60de`.

2021-04-16 10:14 UTC, sangitamane approved these changes

2021-05-18 13:32 UTC, merged